M48
; DRILL file KiCad 10.0.4 date 2026-07-11T13:21:46
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-11T13:21:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.988
%
G90
G05
T1
X102.92Y-119.96
X113.08Y-119.96
T2
X108.0Y-119.96
M30
